### ISSUE TITLE
Printing support

### ISSUE THREAD

**Issue by jimmereeno** [kylelaker/nyt-crossword-download#1]
Thank you in advance for this script!

(I'm a novice, so please bear that in mind when reading my basic vocabulary and replies!)

I have successfully installed and run the script.  As hoped, I am successfully able to download the latest .pdf using the simple command "download.py".  (an "out" folder is automatically generated for the output.) 

My goal is to schedule and run this script daily, sending to my network printer... so I next proceeded to try the following: "download.py --print"
Unfortunately, I get a bundle of errors when I try this (see attached .txt file)

any insights would be greatly appreciated!
-Bob
[error.txt](https://github.com/kylelaker/nyt-crossword-download/files/15170761/error.txt)

**Comment by laurelmay** [comment]
Hi! So sorry that automatic printing isn't working but I am glad to hear that you've at least been able to get the script running to perform the downloads! From your logs, it looks like you're using this on Windows where I haven't actually tested this yet. The printing support in the script is very naive (it directly invokes a command, `lp`, that is only available on Linux and perhaps on macOS).

It looks like on Windows, PowerShell may natively support printing (at least according to https://mendelson.org/pdftoprinter.html) to the default printer. So I maybe be able to add a call to get it to work using an approach like that if the script is being run on Windows. I will investigate further soon (hopefully no later than this weekend) and follow-up once I've got a better idea of whether supporting Windows will be viable.

Thanks for raising this issue!

**Comment by jimmereeno** [comment]
Thank you, so much for the reply! Any attempt would be appreciated. 
You might be interested to hear that I was pointed to your script by chatgpt as a solution to my attempt to download and print the crossword each day. 
Thanks again. - Bob

 
 
  On Wed, May 1, 2024 at 6:37 PM, Kyle ***@***.***> wrote:   


Hi! So sorry that automatic printing isn't working but I am glad to hear that you've at least been able to get the script running to perform the downloads! From your logs, it looks like you're using this on Windows where I haven't actually tested this yet. The printing support in the script is very naive (it directly invokes a command, lp, that is only available on Linux and perhaps on macOS).

It looks like on Windows, PowerShell may natively support printing (at least according to https://mendelson.org/pdftoprinter.html) to the default printer. So I maybe be able to add a call to get it to work using an approach like that if the script is being run on Windows. I will investigate further soon (hopefully no later than this weekend) and follow-up once I've got a better idea of whether supporting Windows will be viable.

Thanks for raising this issue!

**Comment by laurelmay** [comment]
I believe that this was fixed in #2 and that has been merged into the `main` branch! You should be able to pull the new code using `git pull` if you initially cloned the repository using `git`. Feel free to re-open this issue or create a new one if you're still having issues printing on Windows!
